### PR TITLE
Add ability to override Manufacturer and FriendlyName

### PR DESCRIPTION
**Pull request by AshleyMedway**
This was useful at least for what I needed to do.

Also fixed the documentation :)

Great project 👍

### CODE REVIEW

**Comment by eelcocramer** [comment]
Thank you for the PR!

Maybe you can add documentation on how to use the `friendlyName` & `manufacterer`?

**Comment by AshleyMedway** [comment]
Sure shall I just update the example? There's no doc in the readme for custom devices, or did you want to start a wiki?

**Comment by eelcocramer** [comment]
Great thanks a lot!

**Comment by eelcocramer** [comment]
Published to npm as version 0.2.0

**Pull request merged**
